- name: mysql configuration
  hosts: mysql
  become: yes
  vars_files:
  - /var/expense/credentials.yml   #this is the ansible vault file which contains credentials of expense project's DB's password
  roles:
  - mysql